import Head from 'next/head'
import React from 'react'
import { Button, Card, Container, Flex, Input, InputGroup, InputRightElement, Spacer, Tab, TabList, TabPanel, TabPanels, Table, TableContainer, Tabs, Tbody, Td, Text, Textarea, Th, Thead, Tr } from '@chakra-ui/react'
import moment from 'moment'
import { useRouter } from 'next/router'
import { useAppContext } from '@/context/auth'
import Link from 'next/link'
import { AddIcon, ArrowForwardIcon, ArrowRightIcon, CloseIcon } from '@chakra-ui/icons'

export default function CreateProject() {
    const {user} = useAppContext()
    const router = useRouter()
    const [projectName, setProjectName] = React.useState('')
    const [files, setFiles] = React.useState([])
    const [youtubeLinks, setYoutubeLinks] = React.useState<string[]>([])
    const [youtubeLinkInput, setYoutubeLinkInput] = React.useState('')
    const [webLinks, setWebLinks] = React.useState<string[]>([])
    const [webLinkInput, setWebLinkInput] = React.useState('')
    const [textParagraphs, setTextParagraphs] = React.useState([])
    React.useEffect(() => {
        console.log(user)
        if(user == null){
            router.push('/auth')
        }
    }, [])
    const saveProject = () => {
        console.log("saving...")
    }
    React.useEffect(() => {
        console.log(projectName)
    }, [projectName])
    const addYoutubeLink = () => {
        setYoutubeLinks([...youtubeLinks, youtubeLinkInput])
        console.log([...youtubeLinks, youtubeLinkInput])
        setYoutubeLinkInput("")
    }
    const addWebLinks = () => {
        setWebLinks([...webLinks, webLinkInput])
        console.log([...webLinks, webLinkInput])
        setWebLinkInput("")
    }
    return (
        <>
        <Head>
            <title>Project List</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {
            user != null? (
                <main>
                    <Container marginY="20">
                    <Text fontSize="2xl" textAlign='center' fontWeight='bold' marginBottom="8">New Project</Text>
                    <Text marginBottom="4">You can enter or upload multiple types of media here, including plain text, PDF/Word files and URLs of YouTube and websites. Why not try it out below!</Text>
                    <Card padding="4" gap="2" bgColor="gray.100" letterSpacing="0">
                        <Text fontSize="lg" marginBottom="2" fontWeight="bold">Input Section</Text>
                        <Text fontSize="md" marginTop="2">Please enter the name of your project:</Text>
                        <Input placeholder='Enter the name of your project' value={projectName} onChange={(e)=>setProjectName(e.target.value)} />
                        <Text fontSize="md" marginTop="2">Please upload files here:</Text>
                        <Text fontSize="md" marginTop="2">Please enter plain text here:</Text>
                        <Textarea placeholder='Plain text:' />
                        <Text fontSize="md" marginTop="2">Please enter web URLs here:</Text>
                        <InputGroup>
                            <Input placeholder='Web URLs:' value={webLinkInput} onChange={(e)=>setWebLinkInput(e.target.value)} />
                            <InputRightElement>
                                <Button onClick={()=>addWebLinks()} variant="link" isDisabled={webLinkInput.length==0}><AddIcon color='green.500' /></Button>
                            </InputRightElement>
                        </InputGroup>
                        {
                            webLinks.map((link, index) => {
                                return(
                                    <Flex gap="1" marginLeft="2">
                                        <Text fontSize="md" key={link} letterSpacing="0">{link}</Text>
                                        <Spacer />
                                        <Button variant="link" onClick={()=>setWebLinks(webLinks.filter((value)=>value!=link))}>
                                            <CloseIcon color="red.500" />
                                        </Button>
                                    </Flex>
                                )
                            })
                        }
                        <Text fontSize="md" marginTop="2">Please enter YouTube Links here:</Text>
                        <InputGroup>
                            <Input placeholder='Youtube Links' value={youtubeLinkInput} onChange={(e)=>setYoutubeLinkInput(e.target.value)} />
                            <InputRightElement>
                                <Button onClick={()=>addYoutubeLink()} variant="link" isDisabled={youtubeLinkInput.length==0}><AddIcon color='green.500' /></Button>
                            </InputRightElement>
                        </InputGroup>
                        {
                            youtubeLinks.map((link, index) => {
                                return(
                                    <Flex gap="1" marginLeft="2">
                                        <Text fontSize="md" key={link}>{link}</Text>
                                        <Spacer />
                                        <Button variant="link" onClick={()=>setYoutubeLinks(youtubeLinks.filter((value)=>value!=link))}>
                                            <CloseIcon color="red.500" />
                                        </Button>
                                    </Flex>
                                )
                            })
                        }
                        <Flex marginTop="4">
                            <Button onClick={()=>router.back()} bgColor="gray.200">Back</Button>   
                            <Spacer />
                            <Button onClick={() => saveProject()} bgColor="#91FF64" border="2px">
                                Save
                            </Button>
                        </Flex>
                    </Card>
                    
                    <Card padding="4" gap="2" bgColor="gray.100" letterSpacing="0" marginTop="4">
                        <Text fontSize="lg" marginBottom="2" fontWeight="bold">Testing Section</Text>
                        <Textarea placeholder='Enter a prompt to ask questions!' />
                        <Flex marginTop="2">
                            <Spacer />
                            <Button bgColor="#91FF64" border="2px">Chat!</Button>
                        </Flex>
                    </Card>
                    </Container>
                </main>
            ):<></>
        }
    </>
    )
}

