import Head from 'next/head'
import React from 'react'
import { Button, Card, Container, Flex, Input, Spacer, Tab, TabList, TabPanel, TabPanels, Tabs, Text } from '@chakra-ui/react'
import { useAppContext } from "../context/auth"
import { useRouter } from 'next/router'

export default function Auth() {
  const {setUser} = useAppContext()
  const router = useRouter()
  const [loginUser, setLoginUser] = React.useState({
    username: '',
    password: ''
  })
  const [signupUser, setSignupUser] = React.useState({
    username: '',
    password: '',
    password2: ''
  })
  const handleLoginInput = (event: any) => {
    setLoginUser({...loginUser, [event.target.id]: event.target.value })
  }
  const handleSignupInput = (event: any) => {
    setSignupUser({...signupUser, [event.target.id]: event.target.value })
  }
  const containsNumbersAndSymbols = (str: String) => {
    for (let i = 0; i < str.length; i++) {
      const charCode = str.charCodeAt(i);
      if ((charCode >= 48 && charCode <= 57) || // Check if character is a number
          (charCode >= 33 && charCode <= 47) || // Check if character is a symbol
          (charCode >= 58 && charCode <= 64) || // Check if character is a symbol
          (charCode >= 91 && charCode <= 96) || // Check if character is a symbol
          (charCode >= 123 && charCode <= 126)) { // Check if character is a symbol
        return true;
      }
    }
    return false;
  }
  const isValid = () => {
    return signupUser.username.length > 5 && signupUser.password.length > 5 && signupUser.password === signupUser.password2 && containsNumbersAndSymbols(signupUser.password)
  }
  React.useEffect(() => {
    console.log(signupUser)
  }, [signupUser])
  React.useEffect(() => {
    console.log(loginUser)
  }, [loginUser])
  const login = () => {
    fetch('/api/hello')
      .then((res) => res.json())
      .then((data) => {
        setUser({username: data.username})
        router.push('/projects')
      })
  }
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container marginY="16">
          <Text fontSize="2xl" textAlign='center' fontWeight='bold'>Sign in to 852Shepherd</Text>
          <Card bgColor="gray.100" marginY="10" padding="4">
            <Tabs colorScheme="red">
              <TabList>
                <Tab onClick={()=>setSignupUser({ username: '', password: '', password2: ''})}>Login</Tab>
                <Tab onClick={()=>setLoginUser({ username: '', password: ''})}>Signup</Tab>
              </TabList>

              <TabPanels>
                <TabPanel>
                  <Input placeholder='Enter your username' value={loginUser.username} onChange={handleLoginInput} id="username" marginY="2" />
                  <Input placeholder='Enter your password' type="password" value={loginUser.password} onChange={handleLoginInput} id="password" marginY="2" />
                  <Flex>
                    <Spacer />
                    <Button bgColor="#91FF64" border="2px" onClick={()=>login()}>Login</Button>
                  </Flex>
                </TabPanel>
                <TabPanel>
                <Input placeholder='Enter your username' value={signupUser.username} onChange={handleSignupInput} id="username" marginY="2" />
                <Input placeholder='Enter your password' type="password" value={signupUser.password} onChange={handleSignupInput} id="password" marginY="2" />
                <Input placeholder='Re-enter your password' type="password" value={signupUser.password2} onChange={handleSignupInput} id="password2" marginY="2" />
                <Flex>
                  <Spacer />
                  <Button isDisabled={!isValid()} bgColor="#91FF64" border="2px">Sign Up</Button>
                </Flex>
                </TabPanel>
              </TabPanels>
            </Tabs>
          </Card>
        </Container>
      </main>
    </>
  )
}
